spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATA_BASE_URL}
    username: ${DATA_BASE_USERNAME}
    password: ${DATA_BASE_PASSWORD}
    type: com.zaxxer.hikari.HikariDataSource
  rabbitmq:
    addresses: ${RABBIT_ADDRESSES}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}

southsystem:
  s3:
    bucket-name: southsystem
    base-url: https://s3.amazonaws.com/
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}