apiVersion: v1
kind: Service
metadata:
  name: southsystem-process-cluster-ip-service
spec:
  type: ClusterIP
  ports:
    - port: 9001
      targetPort: 9001
  selector:
    component: southsystem-process

